# see https://symfony.com/doc/current/reference/configuration/framework.html
# config/packages/framework.yaml

framework:
    secret: '%env(APP_SECRET)%'
    annotations: false
    http_method_override: false
    handle_all_throwables: true

    # Enable session support with default handler
    session:
        enabled: true
        handler_id: null # You can leave this or set it to null to use default handler
        cookie_secure: auto
        cookie_samesite: lax

    php_errors:
        log: true

# Configuration for the test environment
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
