knp_paginator:
    page_range: 5                       # Nombre de pages à afficher
    default_options:
        page_name: page                 # Nom du paramètre de page dans l'URL
        sort_field_name: sort           # Nom du paramètre de tri
        sort_direction_name: direction  # Nom du paramètre de tri directionnel
        distinct: true                  # Assure que la requête soit distincte
    template:
        pagination: 'pagination.html.twig'     # Template personnalisé pour la pagination
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'
