parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads'

services:
    # Automatically enable autowiring and autoconfiguration
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        #bind:
            #$session: '@session'

    # Explicit definition for CartService
    Symfony\Component\HttpFoundation\Session\SessionInterface: '@session'

    # Make all classes in src/ available as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # StripeService definition
    App\Service\StripeService:
        arguments:
            $stripeSecretKey: '%env(STRIPE_SECRET_KEY)%'
